export const STATUS_CODES = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    NOT_AUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    // 추가 상태 코드 정의 가능...
};

export const MESSAGES = {
    USER: {
        INVALID_USER_ID: 'invalid_user_id',
        INVALID_USER_EMAIL: 'invalid_email',
        INVALID_USER_PASSWORD: 'invalid_password',
        INVALID_USER_NICKNAME: 'invalid_nickname',
        INVALID_EMAIL_OR_PASSWORD: 'invalid_email_or_password',
        NOT_FOUND_USER: 'not_found_user',
        SIGNUP_SUCCESS: 'signup_success',
        LOGIN_SUCCESS: 'login_success',
        UPDATE_USER_SUCCESS: 'update_user_success',
        CHANGE_PASSWORD_SUCCESS: 'change_password_success',
        DELETE_USER_SUCCESS: 'delete_user_success',
        AVAILABLE_EMAIL: 'available_email',
        ALREADY_EXIST_EMAIL: 'already_exist_email',
        AVAILABLE_NICKNAME: 'available_nickname',
        ALREADY_EXIST_NICKNAME: 'already_exist_nickname',
    },
    COMMENT: {
        INVALID_COMMENT_ID: 'invalid_comment_id',
        INVALID_COMMENT_CONTENT: 'invalid_comment_content',
        INVALID_COMMENT_CONTENT_LENGTH: 'invalid_comment_content_length',
        WRITE_COMMENT_SUCCESS: 'write_comment_success',
        NOT_A_SINGLE_COMMENT: 'not_a_single_comment',
        UPDATE_COMMENT_SUCCESS: 'update_comment_success',
        DELETE_COMMENT_SUCCESS: 'delete_comment_success',
    },
    POST: {
        INVALID_POST_ID: 'invalid_post_id',
        INVALID_POST_TITLE: 'invalid_post_title',
        INVALID_POST_CONTENT: 'invalid_post_content',
        INVALID_POST_CONTENT_LENGTH: 'invalid_post_content_length',
        INVALID_POST_TITLE_LENGTH: 'invalid_post_title_length',
        INVALID_OFFSET_LIMIT: 'invalid_offset_or_limit',
        NOT_A_SINGLE_POST: 'not_a_single_post',
        WRITE_POST_SUCCESS: 'write_post_success',
        UPDATE_POST_SUCCESS: 'update_post_success',
        DELETE_POST_SUCCESS: 'delete_post_success',
    },
    FILE: {
        INVALID_FILE: 'invalid_file',
        INVALID_FILE_PATH: 'invalid_file_path',
        FILE_UPLOAD_SUCCESS: 'file_upload_success',
    },
    DB_ERROR: 'database_error',
    QUERY_ERROR: 'query_error',
    NOT_A_SINGLE_POST: 'not_a_single_post',
    INTERNAL_SERVER_ERROR: 'internal_server_error',
    NOT_AUTHORIZED: 'not_authorized',
    // 추가 메시지 정의 가능...
};
